services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=foodsharing_db
      - DB_PORT=5432
      - JWT_SECRET=supersecretkey
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodsharing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
